# Site settings
title: Hardathon
description: "Хардатон, 2017, Москва"
email: info@hardathon.ru
url: http://hardathon.ru

# Social networks usernames
social:
  - title: facebook
    url: https://www.facebook.com/events/1758370364390432/
  - title: vk
    url: http://vk.com/hardathon
